# Generated by Django 6.1 on 2026-08-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaloriesData',
            new_name='EmployeeData',
        ),
    ]
