# Generated by Django 6.1.1 on 2026-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_rename_caloriesdata_employeedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=100)),
                ('JobRole', models.CharField(max_length=100)),
                ('MonthlyIncome', models.CharField(max_length=100)),
                ('OverTime', models.CharField(max_length=100)),
                ('Prediction', models.CharField(max_length=100)),
                ('Probability', models.CharField(max_length=100)),
            ],
        ),
    ]
